config/routes.rb
require 'sti'

Friskyfactory::Application.routes.draw do

  root :to => redirect { |params, request|
    load 'sti.rb' if Rails.env.development?
    site_name = request.domain && request.domain.gsub(/\..*$/, '')
    if site = Site.find_by_name(site_name)
      wave = site.home_wave
      type = wave.class.name.demodulize.downcase.pluralize
      "/wave/#{type}/#{wave.id}"
    end
  }

  get '/assets/:site_name(/:controller_name).:format' => 'admin/sites#stylesheets'

  get '/h/:hash_key(/:style)' => 'posting/postings#show'

  # Waves
  namespace :wave do
    resources :communities, :only => [ :show ] do
      get :rollcall, :path => 'rollcall(/:tag)', :on => :member
    end
    resources :profiles, :only => [ :index, :show ]
    resources :ambassadors, :only => [ :show ]
    resources :places, :only => [ :show ] do
      get :rollcall, :path => 'rollcall(/:tag)', :on => :member
    end
    resources :conversations, :only => [ :index, :show ] do
      member do
        put :close
        get :popup
      end
    end
    resources :albums, :only => [ :index, :show, :new, :create ]
    # resources :events, :only => [ :index, :show, :new, :create ]
  end

  # Wave Functions
  scope :module => :wave do
    resources :waves, :only => [] do
      member do
        put :unpublish
      end
    end
    get 'inbox(/:tag)', :to => 'conversations#index', :as => 'inbox'
    # get ':slug', :to => 'communities#show', :constraints => { :slug => /\D\w*/ }
  end

  # Waves' Postings
  resources :waves, :only => [] do
    namespace :posting do
      resources :texts,        :only => [ :new, :create ]
      resources :photos,       :only => [ :new, :create, :update, :destroy ]
      resources :post_its,     :only => [ :new, :create ]
      resources :videos,       :only => [ :new, :create ]
      resources :messages,     :only => [ :show, :create ]
      resources :wave_proxies, :only => [ :create ]
      resources :invitations,  :only => [ :new, :create, :edit, :update ]
      resources :links,        :only => [ :new, :create ]
    end
  end

  # Posting Functions
  namespace :posting do
    resources :avatars,  :only => [] { get :comments, :on => :member }
    resources :personas, :only => [] { get :comments, :on => :member }
  end

  scope :module => :posting do
    resources :postings, :only => [ :show, :edit, :update ] do |posting|
      resources :comments, :only => [ :index, :new, :create ]

      with_options :controller => 'postings' do |controller|
        controller.delete :unpublish, :on => :member
        controller.get    :fetch,     :on => :collection
      end
    end
  end

  # Personages and Headshots
  resources :profiles, :only => [ :show, :new, :create, :edit, :update ],
      :controller => 'personages' do
    post :avatar, :on => :new
    get  :online, :on => :collection
    member do
      post :avatar
      put  :enable
      put  :switch
      get  :biometrics
      get  :map
      get  :conversation
      get  :invitations
      get  :photos
    end

    resources :friendships, :only => [ :create ], :controller => 'friendships' do
      collection do
        get ':type', :action => 'index', :as => 'typed'
        get ':type/inverse', :action => 'index', :as => 'inverse_typed'
      end
    end

    namespace :wave do
      resource :photos, :only => [ :show ]
    end
  end

  resource :profile, :only => [ :show ],
      :controller => 'personages',
      :as => 'current_personage'

  get ':persona_type' => 'personages#index',
      :constraints => { :persona_type => /ambassadors|communities|places|conditions/ },
      :as => 'persona_type_profiles'

  resource :user, :only => [ :destroy ], :as => 'current_user_record'

  # Geocode
  # resources :locations, :only => [] do
  #   get 'geocode', :on => :collection
  # end

  # Welcome
  namespace :welcome do
    get  'headshot/:pane', :action => 'headshot', :as => 'headshot'
    post 'signup'
    post 'login'
    get  '(/:invitation_code)', :action => 'show'
  end

  post 'launch' => 'welcome#launch'
  match 'logout' => 'user_sessions#destroy', :via => [ :get, :delete ]

  # Reset passwords
  resources :passwords, :only => [ :new, :create, :edit, :update ]

  resources :user_sessions, :only => [ :destroy ] do
    get 'lurk', :on => :new
  end

  # Admin
  namespace :admin do
    # resources :tags, :except => [ :show ] do
    #   collection { get 'commit' }
    # end
    resources :sites, :except => [ :show, :destroy ] do
      resources :users, :only => [ :index, :show, :update ]
      namespace :invitation do
        resources :sites, :except => [ :destroy ]
      end
    end
  end

end

app/views/layouts/shared/_analytics.haml
- if Rails.env.production? && current_site.analytics_domain_name.present? && current_site.analytics_account_number.present?
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', "#{current_site.analytics_account_number}"]);
    _gaq.push(['_setDomainName', "#{current_site.analytics_domain_name}"]);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    
    $(document).ajaxSend(function(event, xhr, settings) {
      _gaq.push(['_trackPageview', settings.url]);
    });

app/views/layouts/shared/_featured_personages.html.haml
%table{ :border => "0", :cellpadding => "0", :cellspacing => "0", :style => "font-family:Helvetica, Verdana, Arial, sans-serif; font-size:16px" }
  %tr
    %td{ :width => '600', :style => "padding:0; border:0; margin:0;"  }
      %h2{:style => "font-size:18px; line-height:1.3em; margin-bottom:5px; padding-top:15px;" } Some more interesting people to meet on #{site.display_name}.
      %p{:style => "margin-bottom:30px;" }
        There's lots of interesting people waiting to meet you on #{site.display_name}. Log in anytime to meet someone new!
%table{ :border => "0", :cellpadding => "0", :cellspacing => "0", :style => "font-family:Helvetica, Verdana, Arial, sans-serif; font-size:16px" }
  %tr{ :height => '84' }
    - featured_personages.each do |featured_personage|
      %td{ :align => 'center', :width => '84', :valign => 'middle', :style => "padding:0; border:0; margin:0;" }
        = link_to image_tag("http://#{host_with_port}#{featured_personage.avatar.url(:polaroid)}", :size => '80x80', :align => 'left', :border => '0', :style => "padding:1px; border-width:1px; border-style:solid; border-color:#ccc;"), wave_profile_url(featured_personage, :host => host, :only_path => false)
      %td{ :width => '15', :style => "padding:0; border:0; margin:0;" } &nbsp;
  %tr{ :height => '12' }
    - featured_personages.each do |featured_personage|
      %td{ :align => 'center', :width => '84', :valign => 'top', :style => "padding:0; border:0; margin:0; line-height: 1em;" }
        = link_to featured_personage.handle.titleize, wave_profile_url(featured_personage, :host => host, :only_path => false), :style => 'font-size:10px; color:#ccc; text-decoration:none;'
      %td{ :width => '15', :style => "padding:0; border:0; margin:0;" } &nbsp;

app/views/layouts/shared/_featured_personages.text.haml
:plain
  There's lots of interesting people waiting to meet you at #{site.display_name}. Log in anytime to meet someone new!
  
  * Featured Profiles
- featured_personages.each do |featured_personage|
  :plain
    * #{featured_personage.handle.titleize} #{wave_profile_url(featured_personage, :host => host, :only_path => false)}

app/views/layouts/shared/_footer.haml
.page.footer
  %p
    %span
      &copy;&nbsp;#{Date.today.year}&nbsp;FriendFactory&nbsp;LLC, New&nbsp;York,&nbsp;NY

app/views/layouts/shared/_nav.haml
- if wave.writable?(current_user[:id])
  %ul.wave.community.nav
    %li.posting_post_it= link_to 'Status', new_wave_posting_post_it_path(wave), :rel => '#new_posting_post_it'
    %li.posting_text= link_to 'Blog', new_wave_posting_text_path(wave), :rel => '#new_posting_text'
    %li.wave_album= link_to 'Album', new_wave_album_path, :rel => '#new_wave_album'
    %li.posting_video= link_to 'Video', new_wave_posting_video_path(wave), :rel => '#new_posting_video'
    - if false
      %li.wave_event= link_to 'Event', new_wave_event_path, :rel => '#new_event_overlay'
    %li.posting_link= link_to 'Link', new_wave_posting_video_path(wave), :rel => '#new_posting_link'

  = render :partial => 'posting/texts/new', :locals => { :wave => wave }
  = render :partial => 'posting/post_its/new', :locals => { :wave => wave }
  = render :partial => 'wave/albums/new', :locals => { :wave => wave }
  = render :partial => 'posting/links/new', :locals => { :wave => wave }
  = render :partial => 'posting/videos/new', :locals => { :wave => wave }
  =# render :partial => 'layouts/shared/nav.x'
  - if false
    #new_event_overlay.new_post_frame
      = render :partial => 'wave/events/new'

app/views/layouts/shared/_nav.x.haml
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.new_post_frame
  .new_post.status
    %form
      %textarea{:placeholder => "Enter Text..."}
      .foot
        %span.counter 160 characters left
        %input{:name => "", :type => "submit", :value => "Post"}/
        %input{:name => "", :type => "button", :value => "Cancel"}/
  .reaction
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.new_post_frame
  .new_post.blog
    %form
      .body
        %input{:name => "", :placeholder => "Blog Title", :type => "text"}/
        %textarea{:placeholder => "Enter Text"}
      .foot
        %input{:name => "", :type => "submit", :value => "Post"}/
        %input{:name => "", :type => "button", :value => "Cancel"}/
  .reaction
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.new_post_frame
  .new_post.photo
    %form
      .body
        %input{:name => "", :type => "file", :value => ""}/
      .foot
        %input{:name => "", :type => "submit", :value => "Post"}/
        %input{:name => "", :type => "button", :value => "Cancel"}/
  .reaction
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.new_post_frame
  .new_post.video
    %form
      %input{:name => "", :placeholder => "Paste Video URL", :type => "text"}/
      .foot
        %input{:name => "", :type => "submit", :value => "Post"}/
        %input{:name => "", :type => "button", :value => "Cancel"}/
  .reaction
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.new_post_frame
  .new_post.checkin
    %form
      .body
        %input{:name => "", :placeholder => "Where are you?", :type => "text"}/
        %img{:src => "/images/map_placeholder_02.png"}
      .foot
        %input{:name => "", :type => "submit", :value => "Post"}/
        %input{:name => "", :type => "button", :value => "Cancel"}/
  .reaction
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.new_post_frame
  .new_post.itinerary
    %form
      .body
        %label Traveling From:
        %input{:name => "", :placeholder => "Ex: Los Angeles, CA", :type => "text"}/
        %label Traveling To:
        %input{:name => "", :placeholder => "Ex: Manhattan, NY", :type => "text"}/
        %hr/
        %label Departure Date:
        .box
          %select
            %option Month
            :javascript
              for(var i=1; i <=12; i++){
                document.write(''+i+'');
              }
          %select
            %option Day
            :javascript
              for(var i=1; i <=31; i++){
                document.write(''+i+'');
              }
        %label Return Date:
        .box
          %select
            %option Month
            :javascript
              for(var i=1; i <=12; i++){
                document.write(''+i+'');
              }
          %select
            %option Day
            :javascript
              for(var i=1; i <=31; i++){
              	document.write(''+i+'');
              }
        %label Public Event:
        .box
          %select
            %option Yes
            %option No
        %hr/
        %label Trip Summary
        %textarea{:placeholder => "I my trip, I plan to..."}
      .foot
        %span.counter 160 characters left
        %input{:name => "", :type => "submit", :value => "Post"}/
        %input{:name => "", :type => "button", :value => "Cancel"}/
  .reaction
/ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

app/views/layouts/shared/_nobrowser.haml
- unless cookies[:ackNoBrowser].present?
  .noscript
    = link_to "×", '#', :title => 'Close', :class => 'close', :rel => 'nofollow'
    %hgroup
      %h1 Yikes! Upgrade Your Browser!
      %p You're using #{browser.display_name} version #{user_agent.version}. #{current_site.display_name} uses technology not supported by this browser. Consider upgrading to the last version.

app/views/layouts/shared/_noscript.haml
%noscript
  .noscript
    %hgroup
      %h1 Yikes! No Javascript!
      %p #{current_site.display_name} uses Javascript heavily. Best to enable it in your browser's preferences.

app/views/layouts/shared/_reaction-template.haml
%script#reaction-template{ :type => "text/template" }
  {{#posting_base}}
  %ul.comments.fetched
    {{#comments}}
    %li
      .mini_comment{ uid, gid, :id => 'posting_comment_{{id}}' }
        .portrait
          %a{ :href => '{{profile_path}}', :'data-remote' => 'true' }
            %img{ :src => '{{image_path}}', :width => '32', :height => '32', :title => '{{handle}}' }/
        .comment
          %p {{body}}
          %span.date Posted {{updated_at}} ago
          %span.comments
            %a{ :href => '{{posting_comments_path}}?reply={{id}}', :'data-remote' => 'true', :class => 'comments' } Reply
    {{/comments}}
  {{/posting_base}}
  {{#wave_album}}
  %ul.photos.fetched
    {{#comments}}
    %li
      %a{ :href => '{{posting_comments_path}}', :'data-remote' => 'true', :class => 'comments', :remote => true }
        %img{ :src => '{{fetched_image_path}}', :class => 'photo {{orientation}}' }
    {{/comments}}
  %a{ :href => '{{posting_comments_path}}', :'data-remote' => 'true', :class => 'comments footer', :remote => true } Show photos &rarr;
  {{/wave_album}}

app/views/layouts/shared/_sidebar.haml
#sidebar
  #head= link_to image_tag('logo.png', :site => true), root_path

  = render_sidebar_adspace
  = render_sidebar_userspace

  = render_sidebar_home_user
  = render_sidebar_ambassadors_list
  = render_sidebar_communities_list
  = render_sidebar_places_list

  = render_sidebar_search

  = render_sidebar_rollcall
  = render_sidebar_online_rollcall

  = render_sidebar_headshot
  = render_sidebar_tag_cloud
  = render_sidebar_navspace

app/views/layouts/shared/_unpublish_overlay.haml
#unpublish_overlay.overlay
  %h1 Unpublish This Posting?
  %p This posting will be removed for all waves.
  %button{ :class => 'close ok' } OK
  %button{ :class => 'close cancel' } Cancel

app/views/layouts/shared/_users_list.haml
- if user_type = local_assigns[:user_type] || 'users'
  - user_type = user_type.to_s.pluralize
- if users.present?
  %ul.block{ :class => user_type }
    - users.each do |user|
      %li
        .portrait= thimble_image_tag(user)
        = link_to user.handle, url_for(user.profile), :class => 'handle'