config/routes.rb
require 'sti'

Friskyfactory::Application.routes.draw do

  root :to => redirect { |params, request|
    load 'sti.rb' if Rails.env.development?
    site_name = request.domain && request.domain.gsub(/\..*$/, '')
    if site = Site.find_by_name(site_name)
      wave = site.home_wave
      type = wave.class.name.demodulize.downcase.pluralize
      "/wave/#{type}/#{wave.id}"
    end
  }

  get '/assets/:site_name(/:controller_name).:format' => 'admin/sites#stylesheets'

  get '/h/:hash_key(/:style)' => 'posting/postings#show'

  # Waves
  namespace :wave do
    resources :communities, :only => [ :show ] do
      get :rollcall, :path => 'rollcall(/:tag)', :on => :member
    end
    resources :profiles, :only => [ :index, :show ]
    resources :ambassadors, :only => [ :show ]
    resources :places, :only => [ :show ] do
      get :rollcall, :path => 'rollcall(/:tag)', :on => :member
    end
    resources :conversations, :only => [ :index, :show ] do
      member do
        put :close
        get :popup
      end
    end
    resources :albums, :only => [ :index, :show, :new, :create ]
    # resources :events, :only => [ :index, :show, :new, :create ]
  end

  # Wave Functions
  scope :module => :wave do
    resources :waves, :only => [] do
      member do
        put :unpublish
      end
    end
    get 'inbox(/:tag)', :to => 'conversations#index', :as => 'inbox'
    # get ':slug', :to => 'communities#show', :constraints => { :slug => /\D\w*/ }
  end

  # Waves' Postings
  resources :waves, :only => [] do
    namespace :posting do
      resources :texts,        :only => [ :new, :create ]
      resources :photos,       :only => [ :new, :create, :update, :destroy ]
      resources :post_its,     :only => [ :new, :create ]
      resources :videos,       :only => [ :new, :create ]
      resources :messages,     :only => [ :show, :create ]
      resources :wave_proxies, :only => [ :create ]
      resources :invitations,  :only => [ :new, :create, :edit, :update ]
      resources :links,        :only => [ :new, :create ]
    end
  end

  # Posting Functions
  namespace :posting do
    resources :avatars,  :only => [] { get :comments, :on => :member }
    resources :personas, :only => [] { get :comments, :on => :member }
  end

  scope :module => :posting do
    resources :postings, :only => [ :show, :edit, :update ] do |posting|
      resources :comments, :only => [ :index, :new, :create ]

      with_options :controller => 'postings' do |controller|
        controller.delete :unpublish, :on => :member
        controller.get    :fetch,     :on => :collection
      end
    end
  end

  # Personages and Headshots
  resources :profiles, :only => [ :show, :new, :create, :edit, :update ],
      :controller => 'personages' do
    post :avatar, :on => :new
    get  :online, :on => :collection
    member do
      post :avatar
      put  :enable
      put  :switch
      get  :biometrics
      get  :map
      get  :conversation
      get  :invitations
      get  :photos
    end

    resources :friendships, :only => [ :create ], :controller => 'friendships' do
      collection do
        get ':type', :action => 'index', :as => 'typed'
        get ':type/inverse', :action => 'index', :as => 'inverse_typed'
      end
    end

    namespace :wave do
      resource :photos, :only => [ :show ]
    end
  end

  resource :profile, :only => [ :show ],
      :controller => 'personages',
      :as => 'current_personage'

  get ':persona_type' => 'personages#index',
      :constraints => { :persona_type => /ambassadors|communities|places|conditions/ },
      :as => 'persona_type_profiles'

  resource :user, :only => [ :destroy ], :as => 'current_user_record'

  # Geocode
  # resources :locations, :only => [] do
  #   get 'geocode', :on => :collection
  # end

  # Welcome
  namespace :welcome do
    get  'headshot/:pane', :action => 'headshot', :as => 'headshot'
    post 'signup'
    post 'login'
    get  '(/:invitation_code)', :action => 'show'
  end

  post 'launch' => 'welcome#launch'
  match 'logout' => 'user_sessions#destroy', :via => [ :get, :delete ]

  # Reset passwords
  resources :passwords, :only => [ :new, :create, :edit, :update ]

  resources :user_sessions, :only => [ :destroy ] do
    get 'lurk', :on => :new
  end

  # Admin
  namespace :admin do
    # resources :tags, :except => [ :show ] do
    #   collection { get 'commit' }
    # end
    resources :sites, :except => [ :show, :destroy ] do
      resources :users, :only => [ :index, :show, :update ]
      namespace :invitation do
        resources :sites, :except => [ :destroy ]
      end
    end
  end

end

app/models/persona/community.rb
require 'wave_avatar'

class Persona::Community < Persona::Base

  extend ActiveSupport::Memoizable

  self.default_profile_type = 'Wave::Community'

  attr_accessible :description

  validates_presence_of :handle

  def avatar
    super || WaveAvatar.new(user)
  end

  memoize :avatar

end

app/models/wave/community.rb
class Wave::Community < Wave::Base

  def publish_posting_to_waves(posting)
    publish_posting_to_profile_wave(posting)
  end

  def subject
    user.handle
  end

  def writable?(user_id)
    true
  end

end

app/controllers/personages_controller.rb
class PersonagesController < ApplicationController

  extend ActiveSupport::Memoizable

  before_filter :require_user
  before_filter :require_admin, :only => [ :new, :create ]

  helper_method \
      :personage,
      :invitation_wave,
      :paged_users,
      :page_title

  layout 'personage'

  cattr_reader :per_page
  @@per_page = 48

  def index
    @users = users.order('"postings"."updated_at" DESC').scoped
    respond_to do |format|
      format.html { render :layout => 'rollcall' }
    end
  end

  def online
    page_title 'Online'
    @users = users.joins(:user).merge(User.online).merge(User.order_by_most_recent_request).scoped
    respond_to do |format|
      format.html { render 'index', :layout => 'rollcall' }
    end
  end

  def show
    page_title current_user.handle
    @personage = params[:id].present? ? current_user_record.personages.find(params[:id]) : current_user
    respond_to do |format|
      format.html
    end
  end

  def new
    @personage = current_user_record.personages.build(default_attributes)
    respond_to do |format|
      format.html
    end
  end

  def create
    state = params[:personage].delete(:state)
    @personage = current_user_record.personages.build(params[:personage])
    @personage.state = state
    respond_to do |format|
      if @personage.save
        @personage.publish_avatar_to_profile_wave
        session[:personage_id] = @personage.id
        format.html { redirect_to profile_path(@personage) }
      else
        format.html { render :action => 'new' }
      end
    end
  end

  def edit
    page_title current_user.handle
    @personage = params[:id].present? ? current_user_record.personages.find(params[:id]) : current_user
    respond_to do |format|
      format.html
    end
  end

  def update
    @personage = current_user_record.personages.find(params[:id])
    respond_to do |format|
      if personage.update_attributes(params[:personage])
        current_site.home_wave.postings << new_persona_posting
        new_persona_posting.publish!
        format.html { redirect_to profile_path }
        format.json { render :json => { :ok => true }}
      else
        format.html { render :action => 'edit' }
        format.json { render :json => { :ok => false }}
      end
    end
  end

  def switch
    @personage = current_user_session.record.personages.find(params[:id])
    session[:personage_id] = @personage.id
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def avatar
    respond_to do |format|
      avatar = if params[:id] && personage = current_user_record.personages.find_by_id(params[:id])
        pid = "pid-#{personage[:id]}"
        handle = personage.handle
        personage.create_and_publish_avatar_to_profile_wave(params[:posting_avatar])
      else
        handle = current_user.handle
        Posting::Avatar.create(params[:posting_avatar]) do |posting|
          posting.user = current_user
        end
      end
      format.json { render :json => { :url => avatar.url(:polaroid), :title => handle, :pid => pid, :avatar_id => avatar[:id] }, :content_type => 'text/html' }
    end
  end

  def enable
    respond_to do |format|
      begin
        personage = current_user_record.personages.find(params[:id])
        personage.send(params[:personage][:state].to_sym)
        format.json { render :json => { :state => personage.current_state }}
      rescue => exception
        format.json { render :json => { :state => false, :exception => { :class => exception.class.to_s, :message => exception.message }}}
      end
    end
  end

  ### Panes

  def biometrics
    respond_to do |format|
      if personage
        format.html { render :layout => false }
      else
        format.html { render :nothing => true }
      end
    end
  end

  def conversation
    respond_to do |format|
      if @wave = current_user.find_or_create_conversation_with(personage, current_site).mark_as_read
        format.html { render :layout => false }
      else
        format.html { render :nothing => true }
      end
    end
  end

  def invitations
    respond_to do |format|
      if personage
        @invitations = personage.profile.postings.type(Posting::Invitation).order('"postings"."created_at" DESC').limit(Wave::InvitationsHelper::MaximumDefaultImages)
        format.html { render :layout => false }
      else
        format.html { render :nothing => true }
      end
    end
  end

  def photos
    respond_to do |format|
      if personage(:include => :profile)
        @photos = personage.profile.photos.limit(Wave::InvitationsHelper::MaximumDefaultImages)
        format.html { render :layout => false }
      else
        format.html { render :nothing => true }
      end
    end
  end

  def map
    respond_to do |format|
      if personage
        format.html { render :layout => false }
      else
        format.html { render :nothing => true }
      end
    end
  end

  private

  def personage(opts = {})
    @personage ||= begin
      relation = Personage.enabled.site(current_site).includes(:persona).scoped
      if includes = opts.delete(:include)
        relation = relation.includes(includes).scoped
      end
      relation.find(params[:id])
    end
  end

  def paged_users
    @paged_users ||= begin
      users.paginate(:page => params[:page], :per_page => @@per_page)
    end
  end

  def users
    @users ||= begin
      users = Personage.enabled.site(current_site).scoped
      users = users.type(params[:persona_type].singularize).scoped if params[:persona_type]
      users.includes(:persona => :avatar).includes(:profile).scoped
    end
  end

  def new_persona_posting
    @new_persona_posting ||= begin
      Posting::Persona.new do |posting|
        posting.user = current_user
      end
    end
  end

  def page_title(page_title = nil)
    @page_title = page_title unless page_title.nil?
    [ current_site.display_name, @page_title ].compact.join(' - ')
  end

  def invitation_wave
    current_user.find_or_create_invitation_wave_for_site(current_site)
  end

  ###

  def transaction
    ActiveRecord::Base.transaction { yield }
  rescue ActiveRecord::RecordInvalid
    nil
  end

  def default_attributes
    type = params[:type] || 'person'
    { :persona_attributes => { :type => "Persona::#{type.titleize}", :emailable => true }}
  end

end

app/controllers/wave/communities_controller.rb
require 'render_headshot'

class Wave::CommunitiesController < ApplicationController

  include RenderHeadshot

  before_filter :require_user

  helper_method :wave, :paged_postings, :sidebar_rollcall # Show helpers
  helper_method :tags, :paged_rollcall, :paged_authors_order # Rollcall helpers
  helper_method :page_title

  layout 'community'

  cattr_reader :per_page
  @@per_page = 50

  def show
    respond_to do |format|
      format.html { request.xhr? ? render_headshot(params[:id]) : render }
    end
  end

  def rollcall
    respond_to do |format|
      format.html { render :layout => 'rollcall' }
    end
  end

  private

  def wave
    @wave ||= begin
      if params[:id].present?
        current_site.waves.published.find(params[:id])
      else
        current_site.home_wave
      end
    end
  end

  def postings
    @postings ||= begin
      debugger
      set_name = current_user.id
      wave.wave_postings.interstore "crap",  [ Posting::Base.published_postings.key ]
      posting_ids = Redis::SortedSet.new("crap").members
      debugger
      postings = Posting::Base.find posting_ids
    #   wave.postings.natural_order.published.joins(:user).merge(Personage.enabled).scoped
    end
  end

  def paged_postings
    @paged_postings ||= begin
      postings.includes(:user => { :persona => :avatar }).
          paginate(:page => params[:page], :per_page => @@per_page)
    end
  end

  def sidebar_rollcall
    @sidebar_rollcall ||= begin
      paged_postings.map(&:user).uniq.select { |user| user[:id] != wave[:user_id] }
    end
  end

  def paged_authors_order
    @paged_postings ||= begin
      wave.postings.authors_order.paginate(:page => params[:page], :per_page => @@per_page)
    end
  end

  def paged_rollcall
    @paged_rollcall ||= begin
      personages = wave.personages.where(%{"personages"."id" in (?)}, paged_authors_order.map(&:user_id))
      paged_authors_order.inject([]) do |rollcall, posting|
        rollcall << personages.detect { |personage| personage.id == posting.user_id }
      end
    end
  end

  def tags
    @tags ||= begin
      personas.tag_counts.order('"name" ASC').select{ |tag| tag.count > 1 }
    end
  end

  def personas
    @personas ||= begin
      user_ids = postings.map(&:user_id)
      Persona::Base.joins(:user).where(:personages => { :id => user_ids }).scoped
    end
  end

  ###

  def parameterize_tag(tag)
    tag.downcase.gsub(/-/, ' ')
  end

  def page_title
    "#{current_site.display_name} - #{wave.subject}"
  end

end

app/helpers/personages_helper.rb
module PersonagesHelper

  def render_headshot personage, opts = {}
    personage = Personage.includes(:persona => :avatar).find(posting[:user_id]) if personage.nil?
    render :partial => File.join('personages', personage.persona_type, 'headshot'), :locals => { :personage => personage }.merge(opts)
  end

  def headshot_image_tag(persona, opts = {})
    if persona && persona.avatar
      opts.merge!(:size => '190x190', :alt => persona.handle, :title => persona.handle)
      image_tag(persona.avatar.url(:polaroid), opts)
    elsif persona
      Rails.logger.warn "Persona:#{persona.id} has no avatar"
      content_tag(:span, "&nbsp;".html_safe, :class => 'headshot-with-error', :style => 'display:inline-block;width:190px;height:190px;')
    end
  end

  def build_empty_personage(personage)
    personage.build_persona
    personage
  end

  def personage_options_for_select
    Persona::Base.types.map { |p| [ p.demodulize, p ] }.sort_by { |p| p.first }
  end

  def poke_css_class(personage_id)
    if current_user && current_user[:id] != personage_id
      current_user.has_poked?(personage_id) && 'poked'
    end
  end

  def link_to_send_cocktail(personage)
    if current_user && (current_user[:id] != personage[:id])
      handle = personage.handle
      handle = nil if handle.length > 7
      msg    = [ 'Send', handle, 'a Cocktail']

      if current_user.has_poked?(personage[:id])
        msg = msg.unshift("Don't")
        disable_with = "Trashing cocktail..."
      else
        disable_with = "Sending cocktail..."
      end

      link_to(msg.compact.join(' '), profile_friendships_path(personage, :type => 'poke'),
          :class => 'poke', :remote => true, :method => :post, :'data-type' => :json, :'data-disable-with' => disable_with)
    end
  end

  def show_or_edit_headshot_pane(personage, pane)
    persona_type, pane = pane.split('/')
    action = (params[:pane] == pane) || params[:pane].blank? ? 'edit' : 'show'
    render :partial => File.join('personages', persona_type, "#{action}_#{pane}"), :locals => { :personage => personage }
  end

end

app/helpers/wave/community_helper.rb
module Wave::CommunityHelper
end

app/views/personages/community/_biometrics.haml
%table.biometrics
  %tr
    %td.label First Name
    %td.detail= persona.handle
  - if persona.description.present?
    %tr
      %td.detail{ :colspan => '2'}
        = persona.description

app/views/personages/community/_edit.haml
= render :partial => File.join('personages', 'shared', 'avatar'), :locals => { :personage => personage }
= render :partial => File.join('personages', 'community', 'edit_biometrics'), :locals => { :personage => personage }
= render :partial => File.join('personages', 'shared', 'preferences'), :locals => { :personage => personage }

app/views/personages/community/_edit_biometrics.haml
= form_for personage, :url => profile_path(personage) do |f|
  = hidden_field_tag :pane, params[:pane], :id => nil
  .headshot-container
    .headshot
      .face
        .pane
          = f.fields_for :persona, personage.persona do |persona_form|
            %table.biometrics
              %tr
                %td.label Name
                %td.detail= persona_form.text_field :handle, :placeholder => 'name', :maxlength => 20, :size => 16
              %tr
                %td.detail{ :colspan => '2' }
                  = persona_form.text_area :description, :placeholder => 'about the community', :maxlength => 200
        .button-bar
          = link_to 'Cancel', profile_path(personage), :class => 'cancel'
          = f.submit 'OK'

app/views/personages/community/_headshot.haml
- persona = personage.persona
- link_to_close_wave_id = local_assigns[:link_to_close_wave_id] || personage[:profile_id]

.headshot-container
  .headshot[ personage ]{ :class => poke_css_class(personage[:id]) }
    .face-container
      .front.face
        = headshot_image_tag(persona)
        = link_to_close(link_to_close_wave_id)
        %span.handle
          = persona.handle
        %ul.buddy-bar.secondary
          - title = "#{persona.handle} Wave"
          %li= link_to title, wave_community_path(personage[:profile_id]), :class => 'icon profile', :title => title
        %ul.buddy-bar.primary
          %li= link_to 'Biometrics', biometrics_profile_path(personage[:id]), :class => 'flip icon mini-profile', :'data-pane-name' => 'biometrics'
    .face-container
      .back.face
        .content
          = link_to_close(link_to_close_wave_id)
          .pane
          .portrait= link_to thimble_image_tag(personage, :size => '18x18'), wave_community_path(personage[:profile_id]), :class => 'flip'

app/views/personages/community/_new.haml
= render :partial => File.join('personages', 'shared', 'new_avatar')
= form_for personage, :url => profiles_path do |form|
  = form.fields_for :persona, personage.persona do |persona_form|
    = persona_form.hidden_field :type
    = persona_form.hidden_field :avatar_id
  = render :partial => File.join('personages', 'community', 'new_biometrics'), :locals => { :form => form }
  = render :partial => File.join('personages', 'shared', 'new_preferences'), :locals => { :form => form }

app/views/personages/community/_new_biometrics.haml
= form.fields_for :persona, personage.persona do |persona_form|
  .headshot-container
    .headshot
      .face
        .pane
          %table.biometrics
            %tr
              %td.label Name
              %td.detail= persona_form.text_field :handle, :placeholder => 'name', :maxlength => 20, :size => 16
            %tr
              %td.detail{ :colspan => '2' }
                = persona_form.text_area :description, :placeholder => 'about the community', :maxlength => 200, :class => 'community_persona_description'

app/views/personages/community/_show.haml
= render :partial => File.join('personages', 'shared', 'avatar'), :locals => { :personage => personage }
= render :partial => File.join('personages', 'community', 'show_biometrics'), :locals => { :personage => personage }
= render :partial => File.join('personages', 'shared', 'preferences'), :locals => { :personage => personage }

app/views/personages/community/_show_biometrics.haml
.headshot-container
  .headshot
    .face
      .pane
        = render :partial => File.join('personages', 'community', 'biometrics'), :locals => { :persona => personage.persona }
      .button-bar
        = link_to 'Change', edit_profile_path(personage), :class => 'button edit_profile'