config/routes.rb
require 'sti'

Friskyfactory::Application.routes.draw do

  root :to => redirect { |params, request|
    load 'sti.rb' if Rails.env.development?
    site_name = request.domain && request.domain.gsub(/\..*$/, '')
    if site = Site.find_by_name(site_name)
      wave = site.home_wave
      type = wave.class.name.demodulize.downcase.pluralize
      "/wave/#{type}/#{wave.id}"
    end
  }

  get '/assets/:site_name(/:controller_name).:format' => 'admin/sites#stylesheets'

  get '/h/:hash_key(/:style)' => 'posting/postings#show'

  # Waves
  namespace :wave do
    resources :communities, :only => [ :show ] do
      get :rollcall, :path => 'rollcall(/:tag)', :on => :member
    end
    resources :profiles, :only => [ :index, :show ]
    resources :ambassadors, :only => [ :show ]
    resources :places, :only => [ :show ] do
      get :rollcall, :path => 'rollcall(/:tag)', :on => :member
    end
    resources :conversations, :only => [ :index, :show ] do
      member do
        put :close
        get :popup
      end
    end
    resources :albums, :only => [ :index, :show, :new, :create ]
    # resources :events, :only => [ :index, :show, :new, :create ]
  end

  # Wave Functions
  scope :module => :wave do
    resources :waves, :only => [] do
      member do
        put :unpublish
      end
    end
    get 'inbox(/:tag)', :to => 'conversations#index', :as => 'inbox'
    # get ':slug', :to => 'communities#show', :constraints => { :slug => /\D\w*/ }
  end

  # Waves' Postings
  resources :waves, :only => [] do
    namespace :posting do
      resources :texts,        :only => [ :new, :create ]
      resources :photos,       :only => [ :new, :create, :update, :destroy ]
      resources :post_its,     :only => [ :new, :create ]
      resources :videos,       :only => [ :new, :create ]
      resources :messages,     :only => [ :show, :create ]
      resources :wave_proxies, :only => [ :create ]
      resources :invitations,  :only => [ :new, :create, :edit, :update ]
      resources :links,        :only => [ :new, :create ]
    end
  end

  # Posting Functions
  namespace :posting do
    resources :avatars,  :only => [] { get :comments, :on => :member }
    resources :personas, :only => [] { get :comments, :on => :member }
  end

  scope :module => :posting do
    resources :postings, :only => [ :show, :edit, :update ] do |posting|
      resources :comments, :only => [ :index, :new, :create ]

      with_options :controller => 'postings' do |controller|
        controller.delete :unpublish, :on => :member
        controller.get    :fetch,     :on => :collection
      end
    end
  end

  # Personages and Headshots
  resources :profiles, :only => [ :show, :new, :create, :edit, :update ],
      :controller => 'personages' do
    post :avatar, :on => :new
    get  :online, :on => :collection
    member do
      post :avatar
      put  :enable
      put  :switch
      get  :biometrics
      get  :map
      get  :conversation
      get  :invitations
      get  :photos
    end

    resources :friendships, :only => [ :create ], :controller => 'friendships' do
      collection do
        get ':type', :action => 'index', :as => 'typed'
        get ':type/inverse', :action => 'index', :as => 'inverse_typed'
      end
    end

    namespace :wave do
      resource :photos, :only => [ :show ]
    end
  end

  resource :profile, :only => [ :show ],
      :controller => 'personages',
      :as => 'current_personage'

  get ':persona_type' => 'personages#index',
      :constraints => { :persona_type => /ambassadors|communities|places|conditions/ },
      :as => 'persona_type_profiles'

  resource :user, :only => [ :destroy ], :as => 'current_user_record'

  # Geocode
  # resources :locations, :only => [] do
  #   get 'geocode', :on => :collection
  # end

  # Welcome
  namespace :welcome do
    get  'headshot/:pane', :action => 'headshot', :as => 'headshot'
    post 'signup'
    post 'login'
    get  '(/:invitation_code)', :action => 'show'
  end

  post 'launch' => 'welcome#launch'
  match 'logout' => 'user_sessions#destroy', :via => [ :get, :delete ]

  # Reset passwords
  resources :passwords, :only => [ :new, :create, :edit, :update ]

  resources :user_sessions, :only => [ :destroy ] do
    get 'lurk', :on => :new
  end

  # Admin
  namespace :admin do
    # resources :tags, :except => [ :show ] do
    #   collection { get 'commit' }
    # end
    resources :sites, :except => [ :show, :destroy ] do
      resources :users, :only => [ :index, :show, :update ]
      namespace :invitation do
        resources :sites, :except => [ :destroy ]
      end
    end
  end

end

app/models/persona/ambassador.rb
require 'geolocation'

class Persona::Ambassador < Persona::Base

  include Geolocation

  self.default_profile_type = 'Wave::Ambassador'

  attr_accessible :location, :description

  validates_presence_of :handle

  def first_name
    self[:first_name].present? ? self[:first_name].strip.titleize : handle
  end

  def last_name
    self[:last_name].strip.titleize if self[:last_name].present?
  end

  def full_name
    [ first_name, last_name ].compact.join(' ')
  end

end

app/models/persona/base.rb
require 'empty_avatar'

class Persona::Base < ActiveRecord::Base

  self.table_name = "personas"

  class_attribute :default_profile_type
  self.default_profile_type = 'Wave::Base'

  acts_as_taggable
  acts_as_taggable_on :locations, :biometrics

  attr_accessible \
      :handle,
      :avatar_id,
      :default,
      :featured,
      :emailable

  before_save :set_tag_list

  has_one :user,
      :class_name  => 'Personage',
      :foreign_key => 'persona_id'

  belongs_to :avatar,
      :class_name => 'Posting::Avatar',
      :autosave   => true

  def build_avatar_with_default_user(avatar_params)
    avatar = build_avatar_without_default_user(avatar_params)
    avatar.user = self.user
    avatar
  end

  alias_method_chain :build_avatar, :default_user

  scope :type, lambda { |*types|
      where(:type => types.map { |type| type.is_a?(Class) ? type.to_s : "Persona/#{type}".camelize })
  }

  scope :site, lambda { |site|
      joins(:user => :user).
      where(:personages => { :users => { :site_id => site.id }})
  }

  scope :has_avatar, where('"avatar_id" is not null')

  scope :featured, where(:featured => true)

  def handle
    self[:handle].strip if self[:handle].present?
  end

  def display_handle
    handle.titleize if handle
  end

  def avatar?
    avatar_without_silhouette.present? && avatar_without_silhouette.published?
  end

  def avatar_with_silhouette
    avatar? ? avatar_without_silhouette : EmptyAvatar.new(self)
  end

  def unpublished_avatar_with_silhouette
    avatar_without_silhouette.present? ? avatar_without_silhouette : EmptyAvatar.new(self)
  end

  alias_method_chain :avatar, :silhouette

  ### Emailable

  def subscribe!
    update_attribute(:emailable, true)
  end

  def unsubscribe!
    update_attribute(:emailable, false)
  end

  private

  def set_tag_list
    # Override in inherited classes
  end

end

app/models/persona/community.rb
require 'wave_avatar'

class Persona::Community < Persona::Base

  extend ActiveSupport::Memoizable

  self.default_profile_type = 'Wave::Community'

  attr_accessible :description

  validates_presence_of :handle

  def avatar
    super || WaveAvatar.new(user)
  end

  memoize :avatar

end

app/models/persona/condition.rb
class Persona::Condition < Persona::Base

  self.default_profile_type = 'Wave::Community'

  attr_accessible :description

  validates_presence_of :handle, :description

end

app/models/persona/person.rb
require 'geolocation'

class Persona::Person < Persona::Base

  include Geolocation

  self.default_profile_type = 'Wave::Profile'

  attr_accessible \
      :first_name,
      :last_name,
      :description,
      :age,
      :location,
      :dob,
      :biometric_values_attributes

  validates_presence_of :handle
  validates_presence_of :age, :location, :on => :create

  has_many :biometric_person_values,
      :class_name  => 'Biometric::PersonValue',
      :foreign_key => 'person_id',
      :autosave    => true

  alias :biometric_values :biometric_person_values

  def biometric_values_attributes=(attributes)
    attributes.each do |domain_id, value_id|
      if domain_id.present? && value_id.present?
        if person_value = biometric_values.find_by_domain_id(domain_id)
          person_value.update_attribute(:value_id, value_id)
        else
          biometric_values.build(:domain_id => domain_id, :value_id => value_id)
        end
      end
    end
  end

  def biometric_value_id(domain)
    if person_value = biometric_person_values.domain(domain).first
      person_value.value_id
    end
  end

  def first_name
    self[:first_name].present? ? self[:first_name].strip.titleize : handle
  end

  def last_name
    self[:last_name].strip.titleize if self[:last_name].present?
  end

  def full_name
    [ first_name, last_name ].compact.join(' ')
  end

  def set_tag_list
    biometric_list = biometric_person_values.map do |biometric_person_value|
      if value = biometric_person_value.value
        value.display_name
      end
    end

    biometric_list = biometric_list.compact.join(',')
    location_list  = [ state, country ].compact.join(',')
    tag_list = [ biometric_list, location_list ].compact.join(',')

    self.location_list  = location_list
    self.biometric_list = biometric_list
    self.tag_list = tag_list
  end

end

app/models/persona/place.rb
require 'geolocation'

class Persona::Place < Persona::Base

  include Geolocation

  self.default_profile_type = 'Wave::Place'

  attr_accessible :location

  validates_presence_of :handle, :location

  def set_tag_list
    location_list = [ state, country ].compact.join(',')
    self.tag_list = location_list
    self.location_list = location_list
  end

end

app/models/posting/persona.rb
class Posting::Persona < Posting::Base

  validates_presence_of :user

  alias_attribute :new_signup, :horizontal

end

app/controllers/posting/personas_controller.rb
class Posting::PersonasController < ApplicationController

  extend ActiveSupport::Memoizable

  before_filter :require_user

  helper_method \
      :posting,
      :personage

  def comments
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  private

  def posting
    Posting::Persona.site(current_site).published.find(params[:id])
  end

  def personage
    Personage.includes(:persona => :avatar).enabled.find(posting[:user_id])
  end

  memoize :posting, :personage

end

app/views/persona/_ambassador.haml
- profile = persona.profile
- link_to_close_wave_id = local_assigns[:link_to_close_wave_id] || profile.id
.headshot-container
  .headshot[ profile ]{ :class => poke_class(profile.id) }
    .face-container
      .front.face
        = headshot_image_tag(profile)
        = link_to_close(link_to_close_wave_id)
        %span.handle
          = profile.handle
        %ul.buddy-bar.primary
          %li= link_to 'Photos', photos_wave_profile_path(profile), :class => 'flip icon photos', :'data-pane-name' => 'photos'
    .face-container
      .back.face
        .content
          = link_to_close(link_to_close_wave_id)
          .pane
          .portrait= link_to thimble_image_tag(profile, :size => '18x18'), wave_profile_path(profile), :class => 'flip'

app/views/persona/_person.haml
- profile = persona.profile
- link_to_close_wave_id = local_assigns[:link_to_close_wave_id] || profile.id
.headshot-container
  .headshot[ profile ]{ :class => poke_class(profile.id) }
    .face-container
      .front.face
        = headshot_image_tag(profile)
        = link_to_close(link_to_close_wave_id)
        %span.handle
          = profile.handle
        %ul.buddy-bar.secondary
          %li= link_to 'Profile', wave_profile_path(profile), :class => 'icon profile'
        %ul.buddy-bar.primary
          %li= link_to 'Biometrics', biometrics_wave_profile_path(profile), :class => 'flip icon mini-profile', :'data-pane-name' => 'biometrics'
          %li= link_to 'Photos', photos_wave_profile_path(profile), :class => 'flip icon photos', :'data-pane-name' => 'photos'
          %li.invitations= link_to 'Invitations', invitations_wave_profile_path(profile), :class => 'flip icon invitations', :'data-pane-name' => 'invitations'
          %li.pokes= link_to 'Pokes', pokes_wave_profile_path(profile), :class => 'flip icon pokes', :'data-pane-name' => 'pokes'
          - if current_user.present? && (current_user.id != profile.user_id)
            - if false
              %li= link_to 'Buddy', buddy_new_friendship_path(profile), :class => buddy_link_class(profile.id), :remote => true, :'data-type' => :json, :method => :put, :'data-pane-name' => 'buddies'
            %li.chat= link_to 'Chat', conversation_wave_profile_path(profile), :class => 'flip icon chat last', :'data-pane-name' => 'conversation'
    .face-container
      .back.face
        .content
          = link_to_close(link_to_close_wave_id)
          .pane
          .portrait= link_to thimble_image_tag(profile, :size => '18x18'), wave_profile_path(profile), :class => 'flip'
          %ul.buddy-bar.primary
            %li= link_to 'Biometrics', biometrics_wave_profile_path(profile), :class => 'swipe icon mini-profile', :'data-pane-name' => 'biometrics'
            %li= link_to 'Photos', photos_wave_profile_path(profile), :class => 'swipe icon photos', :'data-pane-name' => 'photos'
            %li.invitations= link_to 'Invitations', invitations_wave_profile_path(profile), :class => 'swipe icon invitations', :'data-pane-name' => 'invitations'
            %li.pokes= link_to 'Pokes', pokes_wave_profile_path(profile), :class => 'swipe icon pokes', :'data-pane-name' => 'pokes'
            - if current_user.present? && (current_user.id != profile.user_id)
              %li.chat= link_to 'Chat', conversation_wave_profile_path(profile), :class => 'swipe icon chat', :'data-pane-name' => 'conversation'

app/views/persona/_place.haml
- link_to_close_wave_id = local_assigns[:link_to_close_wave_id] || wave.id
.headshot-container
  .headshot[ wave ]{ :class => poke_class(wave.id) }
    .face-container
      .front.face
        = headshot_image_tag(wave)
        = link_to_close(link_to_close_wave_id)
        %span.handle
          PLACE
          = persona.handle
        %ul.buddy-bar.primary
          %li= link_to 'Location', location_wave_profile_path(wave), :class => 'flip icon location', :'data-pane-name' => 'location'
    .face-container
      .back.face
        .content
          = link_to_close(link_to_close_wave_id)
          .pane
          .portrait= link_to thimble_image_tag(wave, :size => '18x18'), wave_place_path(wave), :class => 'flip'