config/routes.rb
require 'sti'

Friskyfactory::Application.routes.draw do

  root :to => redirect { |params, request|
    load 'sti.rb' if Rails.env.development?
    site_name = request.domain && request.domain.gsub(/\..*$/, '')
    if site = Site.find_by_name(site_name)
      wave = site.home_wave
      type = wave.class.name.demodulize.downcase.pluralize
      "/wave/#{type}/#{wave.id}"
    end
  }

  get '/assets/:site_name(/:controller_name).:format' => 'admin/sites#stylesheets'

  get '/h/:hash_key(/:style)' => 'posting/postings#show'

  # Waves
  namespace :wave do
    resources :communities, :only => [ :show ] do
      get :rollcall, :path => 'rollcall(/:tag)', :on => :member
    end
    resources :profiles, :only => [ :index, :show ]
    resources :ambassadors, :only => [ :show ]
    resources :places, :only => [ :show ] do
      get :rollcall, :path => 'rollcall(/:tag)', :on => :member
    end
    resources :conversations, :only => [ :index, :show ] do
      member do
        put :close
        get :popup
      end
    end
    resources :albums, :only => [ :index, :show, :new, :create ]
    # resources :events, :only => [ :index, :show, :new, :create ]
  end

  # Wave Functions
  scope :module => :wave do
    resources :waves, :only => [] do
      member do
        put :unpublish
      end
    end
    get 'inbox(/:tag)', :to => 'conversations#index', :as => 'inbox'
    # get ':slug', :to => 'communities#show', :constraints => { :slug => /\D\w*/ }
  end

  # Waves' Postings
  resources :waves, :only => [] do
    namespace :posting do
      resources :texts,        :only => [ :new, :create ]
      resources :photos,       :only => [ :new, :create, :update, :destroy ]
      resources :post_its,     :only => [ :new, :create ]
      resources :videos,       :only => [ :new, :create ]
      resources :messages,     :only => [ :show, :create ]
      resources :wave_proxies, :only => [ :create ]
      resources :invitations,  :only => [ :new, :create, :edit, :update ]
      resources :links,        :only => [ :new, :create ]
    end
  end

  # Posting Functions
  namespace :posting do
    resources :avatars,  :only => [] { get :comments, :on => :member }
    resources :personas, :only => [] { get :comments, :on => :member }
  end

  scope :module => :posting do
    resources :postings, :only => [ :show, :edit, :update ] do |posting|
      resources :comments, :only => [ :index, :new, :create ]

      with_options :controller => 'postings' do |controller|
        controller.delete :unpublish, :on => :member
        controller.get    :fetch,     :on => :collection
      end
    end
  end

  # Personages and Headshots
  resources :profiles, :only => [ :show, :new, :create, :edit, :update ],
      :controller => 'personages' do
    post :avatar, :on => :new
    get  :online, :on => :collection
    member do
      post :avatar
      put  :enable
      put  :switch
      get  :biometrics
      get  :map
      get  :conversation
      get  :invitations
      get  :photos
    end

    resources :friendships, :only => [ :create ], :controller => 'friendships' do
      collection do
        get ':type', :action => 'index', :as => 'typed'
        get ':type/inverse', :action => 'index', :as => 'inverse_typed'
      end
    end

    namespace :wave do
      resource :photos, :only => [ :show ]
    end
  end

  resource :profile, :only => [ :show ],
      :controller => 'personages',
      :as => 'current_personage'

  get ':persona_type' => 'personages#index',
      :constraints => { :persona_type => /ambassadors|communities|places|conditions/ },
      :as => 'persona_type_profiles'

  resource :user, :only => [ :destroy ], :as => 'current_user_record'

  # Geocode
  # resources :locations, :only => [] do
  #   get 'geocode', :on => :collection
  # end

  # Welcome
  namespace :welcome do
    get  'headshot/:pane', :action => 'headshot', :as => 'headshot'
    post 'signup'
    post 'login'
    get  '(/:invitation_code)', :action => 'show'
  end

  post 'launch' => 'welcome#launch'
  match 'logout' => 'user_sessions#destroy', :via => [ :get, :delete ]

  # Reset passwords
  resources :passwords, :only => [ :new, :create, :edit, :update ]

  resources :user_sessions, :only => [ :destroy ] do
    get 'lurk', :on => :new
  end

  # Admin
  namespace :admin do
    # resources :tags, :except => [ :show ] do
    #   collection { get 'commit' }
    # end
    resources :sites, :except => [ :show, :destroy ] do
      resources :users, :only => [ :index, :show, :update ]
      namespace :invitation do
        resources :sites, :except => [ :destroy ]
      end
    end
  end

end

app/models/metadata/wave.rb
module Metadata
  class Wave < Metadata::Base
    class InvalidWaveIdError < Exception; end

    class << self
      def ingest ingestable
        wave = new ingestable.wave_id
        wave.postings << ingestable.id
        wave
      rescue NoMethodError
        warn ingestable, "missing attribute wave_id"
      rescue InvalidWaveIdError
        warn ingestable, "invalid wave_id"
      end
    end

    attr_reader :id

    set :postings

    def initialize id
      raise InvalidWaveIdError if id.nil?
      @id = id
    end
  end
end

app/models/wave/album.rb
class Wave::Album < Wave::Base

  def photos
    postings.type(Posting::Photo).published.order('"created_at" ASC').scoped
  end

  def fetchables(limit = nil)
    if fetchable?
      limit = (limit.to_i / 2 * 3) if limit.present?
      photos.limit(limit).offset(1).scoped
    else
      super
    end
  end

  def fetch_type
    fetchable? ? :wave_album : super
  end

  private

  def fetchable?
    photos.count > 1
  end

end

app/models/wave/ambassador.rb
class Wave::Ambassador < Wave::Profile

  def subject
    handle
  end

  def writable?(user_id)
    owner?(user_id)
  end

end

app/models/wave/base.rb
class Wave::Base < Posting::Base

  alias_attribute :topic,       :subject
  alias_attribute :description, :body

  scope :site, lambda { |site| joins(:sites).where(:sites => { :id => site[:id] }).readonly(false) }

  has_and_belongs_to_many :sites,
      :class_name              => 'Site',
      :join_table              => 'sites_waves',
      :foreign_key             => 'wave_id',
      :association_foreign_key => 'site_id'

  ###

  sorted_set :wave_postings, key: lambda {|wave| "wave:#{wave.id}:postings" }

  HalfLife = 12.hours.to_f

  def add_posting posting
    wave_postings.add posting.id, posting.updated_at.to_i / HalfLife
  end

  has_many :publications, :foreign_key => 'wave_id'

  has_many :postings,
      :through    => :publications,
      :conditions => { :parent_id => nil } do
    def <<(posting)
      proxy_owner = proxy_association.owner
      proxy_owner.class.transaction do
        parent = proxy_owner.publications.create!(:posting => posting)
        secondary_waves = *proxy_owner.publish_posting_to_waves(posting)
        if secondary_waves.present?
          secondary_waves.delete(proxy_owner)
          secondary_waves.compact.uniq.each do |wave|
            posting.publishables.create!(:wave => wave, :parent => parent)
          end
        end
        posting
      end
    end

    def natural_order
      order('"postings"."sticky_until" DESC, "postings"."primed_at" DESC')
    end

    def authors_order
      select(%{distinct "postings"."user_id", max("postings"."created_at") as created_at}).
      group(%{"postings"."user_id"}).
      merge(Posting::Base.published).
      order("created_at DESC")
    end
  end

  has_many :personages, through: :postings, source: :user, uniq: true

  def publish_posting_to_waves(posting)
    [] # Override in descendant classes
  end

  def publish_posting_to_profile_wave(posting)
    if posting && posting.user
      posting.user.profile
    end
  end

  def publish_posting_to_home_wave(posting)
    @home_wave ||= begin
      if posting && site = posting.site
        site.home_wave
      end
    end
  end

  ###

  has_many :bookmarks, :foreign_key => 'wave_id'

  def rollcall
    @rollcall ||= personages.scoped
  end

  def writable?(user_id)
    false
  end

  ###

  private

  def owner?(user_id)
    user_id == self[:user_id]
  end

end

app/models/wave/buddy.rb
class Wave::Buddy < Wave::Friendship
end

app/models/wave/community.rb
class Wave::Community < Wave::Base

  def publish_posting_to_waves(posting)
    publish_posting_to_profile_wave(posting)
  end

  def subject
    user.handle
  end

  def writable?(user_id)
    true
  end

end

app/controllers/wave/albums_controller.rb
class Wave::AlbumsController < ApplicationController
  
  before_filter :require_user  

  def index
    @waves = Wave::Album.published.order('created_at desc')
  end
    
  def show
    @wave = current_site.waves.find_by_id(params[:id])
    @start_slide = start_slide(params[:photo_id])
    respond_to do |format|
      format.html { render :layout => 'album' }
    end
  end
    
  def create
    @wave = nil
    if params[:wave_id].present?
      @wave = current_site.waves.type(Wave::Album).find_by_id(params[:wave_id])
    end
    unless @wave.present?
      @wave = Wave::Album.new do |wave|
        wave.user = current_user
        wave.state = :unpublished
      end
      if @wave.save
        current_site.waves << @wave
      end
    end
    if @wave.postings << new_posting_photo
      current_user.find_or_create_photos_wave.postings << new_posting_photo
      render :json => created_wave_to_json(@wave, @posting), :content_type => 'text/html'
    else
      render :json => { :result => 'error' }, :content_type => 'text/html'      
    end
  end
    
  private

  def new_posting_photo
    @posting ||= begin
      Posting::Photo.new(params[:posting_photo]).tap do |posting|
        posting.user = current_user
        posting.state = :published
      end
    end
  end
  
  def created_wave_to_json(wave, posting)
    { :wave_id    => wave.id,
      :dom_id     => dom_id(posting),
      :image_path => (posting.horizontal? ? posting.image.url(:h4x6) : posting.image.url(:v4x6)),
      :name       => posting.image.instance.attributes["image_file_name"],
      :horizontal => posting.horizontal? }
  end
  
  def start_slide(photo_id)
    if photo_id.present?
      @wave.photos.each_with_index do |photo, idx|
        return (idx + 1) if photo.id == photo_id.to_i
      end
    end
    1
  end
  
end

app/controllers/wave/ambassadors_controller.rb
require 'resolver'
require 'render_headshot'

class Wave::AmbassadorsController < ApplicationController

  include RenderHeadshot

  extend ActiveSupport::Memoizable

  before_filter :require_user

  helper_method :wave, :postings
  helper_method :page_title

  layout 'community'

  prepend_view_path ::Resolver.new('wave/ambassadors')

  cattr_reader :per_page

  def show
    @@per_page = 50
    respond_to do |format|
      format.html { request.xhr? ? render_headshot(params[:id]) : render }
    end
  end

  private

  def wave
    current_site.waves.type(Wave::Ambassador).includes(:user => :persona).find(params[:id])
  end

  memoize :wave

  def postings
    wave.postings.published.
      includes(:user => { :persona => :avatar }).
      order('"sticky_until" DESC, "updated_at" DESC').
      paginate(:page => params[:page], :per_page => @@per_page)
  end

  memoize :postings

  def page_title
    "#{current_site.display_name} - #{wave.handle}"
  end

end

app/controllers/wave/communities_controller.rb
require 'render_headshot'

class Wave::CommunitiesController < ApplicationController

  include RenderHeadshot

  before_filter :require_user

  helper_method :wave, :paged_postings, :sidebar_rollcall # Show helpers
  helper_method :tags, :paged_rollcall, :paged_authors_order # Rollcall helpers
  helper_method :page_title

  layout 'community'

  cattr_reader :per_page
  @@per_page = 50

  def show
    respond_to do |format|
      format.html { request.xhr? ? render_headshot(params[:id]) : render }
    end
  end

  def rollcall
    respond_to do |format|
      format.html { render :layout => 'rollcall' }
    end
  end

  private

  def wave
    @wave ||= begin
      if params[:id].present?
        current_site.waves.published.find(params[:id])
      else
        current_site.home_wave
      end
    end
  end

  def postings
    @postings ||= begin
      debugger
      set_name = current_user.id
      wave.wave_postings.interstore "crap",  [ Posting::Base.published_postings.key ]
      posting_ids = Redis::SortedSet.new("crap").members
      debugger
      postings = Posting::Base.find posting_ids
    #   wave.postings.natural_order.published.joins(:user).merge(Personage.enabled).scoped
    end
  end

  def paged_postings
    @paged_postings ||= begin
      postings.includes(:user => { :persona => :avatar }).
          paginate(:page => params[:page], :per_page => @@per_page)
    end
  end

  def sidebar_rollcall
    @sidebar_rollcall ||= begin
      paged_postings.map(&:user).uniq.select { |user| user[:id] != wave[:user_id] }
    end
  end

  def paged_authors_order
    @paged_postings ||= begin
      wave.postings.authors_order.paginate(:page => params[:page], :per_page => @@per_page)
    end
  end

  def paged_rollcall
    @paged_rollcall ||= begin
      personages = wave.personages.where(%{"personages"."id" in (?)}, paged_authors_order.map(&:user_id))
      paged_authors_order.inject([]) do |rollcall, posting|
        rollcall << personages.detect { |personage| personage.id == posting.user_id }
      end
    end
  end

  def tags
    @tags ||= begin
      personas.tag_counts.order('"name" ASC').select{ |tag| tag.count > 1 }
    end
  end

  def personas
    @personas ||= begin
      user_ids = postings.map(&:user_id)
      Persona::Base.joins(:user).where(:personages => { :id => user_ids }).scoped
    end
  end

  ###

  def parameterize_tag(tag)
    tag.downcase.gsub(/-/, ' ')
  end

  def page_title
    "#{current_site.display_name} - #{wave.subject}"
  end

end

app/controllers/wave/conversations_controller.rb
class Wave::ConversationsController < ApplicationController

  extend ActiveSupport::Memoizable

  before_filter :require_user

  helper_method :paged_conversations, :tags
  helper_method :page_title

  layout 'inbox'

  cattr_reader :per_page
  @@per_page = 12

  def index
    respond_to do |format|
      format.html
    end
  end

  # def popup
  #   @popup = true
  #   @title = current_site.name
  #   @wave = current_user.conversations.site(current_site).find_by_id(params[:id])
  #   if @wave.present? && @wave.recipient.present?
  #     @title += " with #{@wave.recipient.handle}"
  #   end
  #   respond_to do |format|
  #     format.html { render :action => 'show' }
  #   end
  # end

  def close
    @wave = current_user.inbox(current_site).find(params[:id])
    respond_to do |format|
      @wave.read && @wave.unpublish!
      format.json { render :json => { :closed => true }}
    end
  end

  private

  def paged_conversations
    conversations.paginate(:page => params[:page], :per_page => @@per_page)
  end

  def tags
    personas.tag_counts.order('"name" ASC').select{ |tag| tag.count > 1 }
  end

  memoize :paged_conversations, :tags

  ###

  def conversations
    conversations = params[:tag] ? conversations_from_tagged_personas : conversations_from_all
    conversations.
        includes(:recipient => { :persona => :avatar }).
        order('"postings"."updated_at" DESC').scoped
  end

  def conversations_from_all
    conversations = current_user.inbox(current_site).
        joins(:recipient).
        merge(Personage.enabled).scoped
  end

  memoize :conversations_from_all

  def conversations_from_tagged_personas
    conversations_from_all.where(:resource_id => tagged_personas.map(&:id)).scoped
  end

  def tagged_personas
    tagged_personas = personas
    tagged_personas = personas.tagged_with(parameterize_tag(params[:tag]), :on => :tags).scoped if params[:tag]
    tagged_personas
  end

  def personas
    user_ids = conversations_from_all.map(&:resource_id)
    Persona::Base.joins(:user).where(:personages => { :id => user_ids }).scoped
  end

  def conversation_dates
    current_user.inbox(current_site).
        select('date("postings"."updated_at") AS updated_at, count(*) AS count, array_agg(distinct resource_id) AS recipient_ids').
        group('date("postings"."updated_at")').
        order('date("postings"."updated_at") DESC')
  end

  def parameterize_tag(tag)
    tag.downcase.gsub(/-/, ' ')
  end

  def page_title
    "#{current_site.display_name} - #{current_profile.handle}'s Inbox"
  end

end

app/controllers/wave/events_controller.rb
class Wave::EventsController < ApplicationController

  DefaultEventSlug = 'events'
  
  cattr_reader :per_page
  @@per_page = 30
  
  def index
    @waves = find_events_tagged_with(params[:tag]) || find_all_events
    @tags = tag_counts_on_current_site
    respond_to do |format|
      format.html
    end
  end
  
  def create
    @wave = Wave::Event.new(params[:wave_event]).tap { |event| event.user = current_user }
    if @wave.save
      current_site.waves << @wave
      current_site.home_wave.postings << @wave
      # @wave.set_tag_list_on(current_site) # TODO: Move to before_save callback
      @wave.publish!
    end
    respond_to do |format|
      format.js { render :layout => false }
    end
  end
  
  private
  
  def find_events_tagged_with(tag)
    if tag.present?
      Wave::Event.tagged_with(scrubbed_tag(tag), :on => current_site).
          where(:state => :published).
          order('updated_at desc').
          paginate(:page => params[:page], :per_page => @@per_page)
    end
  end
  
  def find_all_events
    current_site.waves.type(Wave::Event).
        published.
        order('updated_at desc').
        paginate(:page => params[:page], :per_page => @@per_page)      
  end
  
  def scrubbed_tag(tag)
    tag.downcase.gsub(/-/, ' ')
  end
  
  def tag_counts_on_current_site
    Wave::Event.tag_counts_on(current_site).order('name asc')
  end
  
end

app/views/waves/show.html.haml
- javascript 'wave'

:javascript
  jQuery(document).ready(function($){
    $('.tab_content').hide();    
  });
    
.wave.grid_15[@wave]
  .grid_3.alpha.omega
    %p.flash= flash[:notice]
    &nbsp;
  .grid_12.alpha.omega
    - if current_user
      %ul#tabs
        %li
          %a{ :href => '#text' } Text
        %li
          %a{ :href => '#photo' } Photo
        %li
          %a{ :href => '#video' } Video
        %li
          %a{ :href => '#chat' } Chat
        %li
          %a{ :href => '#hottie' } Hottie
        %li
          %a{ :href => '#link' } Link
        %li
          %a{ :href => '#event' } Event
        %li
          %a{ :href => '#poll' } Poll

    %h1= h @wave.topic

    - if current_user
      #text.tab_content.hidden
        %table
          %tr
            %td{ :colspan => '2' }
              %h2 Write a Message to this Wave
          %tr
            %td.avatar.thumb= thumb_image_tag(current_user.profile.avatar)
            %td
              - form_for Posting::Text.new, :url => wave_texts_path(:wave_id => @wave) do |f|
                = f.text_field :subject, :placeholder => 'Title (optional)'
                = f.text_area :body
                = f.submit :OK
                = f.button :Cancel, :class => 'cancel'

      #photo.tab_content.hidden
        %table
          %tr
            %td{ :colspan => '2' }
              %h2 Upload a Photo to the Wave
          %tr
            %td.avatar.thumb= thumb_image_tag(current_user.profile.avatar)
            %td
              - form_for(Posting::Photo.new, :url => wave_photos_path(:wave_id => @wave, :format => :js), :html => { :multipart => true, :target => 'upload_frame' }) do |f|
                %table.button_bar
                  %tr
                    %td.file_field= f.file_field :image
                  %tr
                    %td.submit
                      = f.submit 'Upload Photo', :id => 'photo_upload_submit'
                      = f.button :Cancel, :class => 'cancel'
                      = spinner

      #video.tab_content.hidden
        %table
          %tr
            %td{ :colspan => '2' }
              %h2 Upload a Video to the Wave
          %tr
            %td.avatar.thumb= thumb_image_tag(current_user.profile.avatar)
            %td
              -form_for(Posting::Video.new, :url => wave_videos_path(:wave_id => @wave, :format => :json)) do |f|
                %p.unobtrusive Paste the URL of the YouTube tube here.
                = f.text_area :body
                = f.text_field :subject, :placeholder => 'Caption (optional)'
                = f.submit :OK
                = f.button :Cancel, :class => 'cancel'
        :javascript
          $('#video.tab_content form').submit(function(){
            FF.scrub_placeholders(this);
            jQuery.ajax({
              data: jQuery.param(jQuery(this).serializeArray()),
              dataType: 'script',
              cache: false,
              type: 'post',
              url: '#{wave_videos_path(:wave_id => @wave)}',
              success: function(){
                $('#video.tab_content form')
                .reset()
                .closest('.tab_content').hide();
              $('ul#tabs li.current').removeClass('current');
              }
            });
            return false;
          });

      #chat.tab_content.hidden Chat
      #hottie.tab_content.hidden Hottie
      #link.tab_content.hidden Link
      #event.tab_content.hidden Event
      #poll.tab_content.hidden Poll

      %iframe#upload_frame{ :name => "upload_frame", :width => '1', :height => '1', :style => 'border:0px', :src => 'about:blank' }

    - if false
      #log

  #posting_well
    - @wave.postings.for(current_user).each do |posting|
      - partial = render(:partial => 'postings/posting', :object => posting)
      .grid_3.alpha.omega{ :class => 'sidebar' }
        = yield("#{dom_id(posting)}_sidebar")
      .grid_12.alpha.omega
        = partial

:javascript
  jQuery(document).ready(function($){
    $('#text.tab_content form').submit(function(){
      jQuery.ajax({
        data: jQuery.param(jQuery(this).serializeArray()),
        dataType: 'script',
        cache: false,
        type: 'post',
        url: '#{wave_texts_path(:wave_id => @wave)}',
        success: function(){
          $('#text.tab_content form')
          .reset()
          .closest('.tab_content').hide();
        $('ul#tabs li.current').removeClass('current');
        }
      });
      return false;
    });      
  });